# Generated by Django 5.2.10 on 2026-01-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_categories_category_remove_product_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
